### ISSUE TITLE
Make it so that there is only 1 play and pause button.

### ISSUE THREAD

**Issue by shahzeb1** [shahzeb1/soundcloud-player#1]
If the song is playing then show the pause button.
If the song is paused (or not playing) then show the play button.

The section/code you should focus on: [These lines](https://github.com/shahzeb1/soundcloud-player/blob/master/mySC.js#L13L20).

Good issue for beginners!

**Comment by mohammedri** [comment]
Do you want to remove the button or appear as if it is disabled?

**Comment by shahzeb1** [comment]
Remove the pause button. 

So there would be 1 button. If the song is playing, then clicking the button should pause the song. If the song is paused, then clicking the button should play the song. Icons within the button should change accordingly.

**Comment by R3l4x3** [comment]
I'll take a look into it.
